# Generated by Django 5.2.7 on 2025-10-18 10:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='demo',
            new_name='demo_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('code', 'Source Code'), ('apps', 'Mobile Apps'), ('websites', 'Websites'), ('templates', 'Templates')], default='code', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='file_url',
            field=models.URLField(default='ikpixels.com', help_text='URL to download product/file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='product',
            name='key_features',
            field=models.TextField(default='we', help_text='Enter each feature on a new line starting with •'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='preview_gradient',
            field=models.CharField(choices=[('linear-gradient(135deg, #667eea 0%, #764ba2 100%)', 'Purple Blue'), ('linear-gradient(135deg, #f093fb 0%, #f5576c 100%)', 'Pink Red'), ('linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)', 'Blue Cyan'), ('linear-gradient(135deg, #fa709a 0%, #fee140 100%)', 'Pink Yellow'), ('linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)', 'Mint Pink'), ('linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)', 'Orange Peach'), ('linear-gradient(135deg, #667eea 0%, #764ba2 100%)', 'Indigo Purple')], default='Mint Pink', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='technologies_used',
            field=models.CharField(default='python', help_text='Separate technologies with commas', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
