# Generated by Django 5.2.7 on 2025-10-18 15:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='media',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
